language: objective-c

before_install: 
- brew update
- brew upgrade xctool

script: 
- xctool clean build test -project SoundPlayerDemo.xcodeproj -scheme SoundPlayerDemo -sdk iphonesimulator7.0 ONLY_ACTIVE_ARCH=NO
